### ISSUE TITLE
Internet Unavailable PopUp

### ISSUE THREAD

**Issue by shuhanmirza** [sustcast/sustcast-android-app-v1#11]

**Comment by istiakshihab** [comment]
Added an internet checker to `LandingActivity`.
Why `LandingActivity` only?
- It only made sense because `authChecking` will be happening in `SplashActivity` anyway and on failure will be returned to `LandingActivity`. So in case of internet failure, it will go to that specific activity.

@shuhanmirza Please close the issue if you are satisfied with the approach.

**Comment by shuhanmirza** [comment]
I think we should have a helper function. So that we can check connectivity from any activity. And if connectivity is not present, a dialog popup will be shown or every activity will just be directed to the landing activity.

Sounds right?

**Comment by istiakshihab** [comment]
Yes, I did that. But is it necessary to check this in every activity that gets redirected from `LandingActivity` as it's the parent layout anyway?  by every activity, I meant `LoginActivty` `SignUpActivity` and others.
Make an issue for @appledora if you want it to be used in her fragments too.

**Comment by shuhanmirza** [comment]
Let's discuss this on next meeting.

**Comment by istiakshihab** [comment]
Closing issue.
